# Generated by Django 5.2.9 on 2025-12-25 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('KR', '국내'), ('US', '해외')], max_length=2, unique=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('KR', '국내'), ('US', '해외')], db_index=True, max_length=2)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('change_percent', models.FloatField(default=0.0)),
                ('market_cap', models.BigIntegerField(db_index=True, default=0)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-market_cap'],
                'indexes': [models.Index(fields=['market', '-market_cap'], name='stocks_stoc_market_4651b0_idx')],
            },
        ),
    ]
