# Generated by Django 5.2.9 on 2025-12-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
        ('news', '0003_remove_news_is_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_news',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='news.news'),
        ),
    ]
