# Generated by Django 5.2.9 on 2025-12-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('kor_co_cm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=150)),
                ('join_deny', models.IntegerField()),
                ('join_member', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField(blank=True, default='')),
                ('etc_note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('rsrv_type', models.CharField(max_length=30)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('intr_rate_type_nm', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.depositproduct')),
            ],
        ),
    ]
