# Generated by Django 5.2.9 on 2025-12-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositproduct',
            old_name='kor_co_cm',
            new_name='kor_co_nm',
        ),
    ]
