# Generated by Django 5.2.9 on 2025-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_kor_co_cm_depositproduct_kor_co_nm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=150)),
                ('join_deny', models.IntegerField()),
                ('join_member', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField(blank=True, default='')),
                ('etc_note', models.TextField(blank=True, default='')),
            ],
        ),
    ]
