# Generated by Django 5.2.9 on 2025-12-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_savingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('rsrv_type', models.CharField(max_length=30)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('intr_rate_type_nm', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.savingproduct')),
            ],
        ),
    ]
