# Generated by Django 5.2.9 on 2025-12-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='fin_prdt_cd',
            field=models.CharField(max_length=50),
        ),
    ]
