# Generated by Django 5.2.9 on 2025-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=20, unique=True)),
                ('cur_nm', models.CharField(max_length=100)),
                ('ttb', models.CharField(blank=True, max_length=20)),
                ('tts', models.CharField(blank=True, max_length=20)),
                ('deal_bas_r', models.CharField(blank=True, max_length=20)),
                ('bkpr', models.CharField(blank=True, max_length=20)),
                ('kftc_deal_bas_r', models.CharField(blank=True, max_length=20)),
                ('kftc_bkpr', models.CharField(blank=True, max_length=20)),
                ('search_date', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
