# Generated by Django 5.2.9 on 2025-12-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='apartment_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='current_savings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('purchase', '매매'), ('jeonse', '전세'), ('wolse_deposit', '월세 보증금'), ('wolse', '월세')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='savings_purpose_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='target_apartment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='target_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='travel_country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='travel_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='ai_verdict',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='alternative_plans',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='combination_strategy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='exchange_rate_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='final_amount_in_currency',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='goal_math',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='real_estate_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='recommended_destinations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='recommended_properties',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='related_news',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='related_videos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='strategy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendationresult',
            name='travel_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='purpose',
            field=models.CharField(choices=[('housing', '주택'), ('savings', '목돈'), ('travel', '여행')], max_length=50),
        ),
    ]
