# Generated by Django 5.2.9 on 2025-12-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('pub_date', models.CharField(max_length=50)),
                ('is_bookmarked', models.BooleanField(default=False)),
            ],
        ),
    ]
