# Generated by Django 5.2.9 on 2025-12-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
