# Generated by Django 5.2.9 on 2025-12-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_pub_date_news_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_bookmarked',
        ),
    ]
