# Generated by Django 5.2.9 on 2025-12-22 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_all_news(apps, schema_editor):
    """기존 뉴스 데이터를 모두 삭제"""
    News = apps.get_model("news", "News")
    News.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_news_is_bookmarked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 기존 뉴스 데이터 삭제
        migrations.RunPython(delete_all_news, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="news",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="news",
            unique_together={("user", "title")},
        ),
    ]
